# Generated by Django 5.2.2 on 2025-06-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="title",
            new_name="text",
        ),
    ]
